# Generated by Django 4.1.3 on 2022-11-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_edad_persona_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrantes',
            name='profesion',
            field=models.CharField(default=30, max_length=50),
            preserve_default=False,
        ),
    ]
